'use strict';
/**
 * reparse-cache.js — Re-parse tất cả rawResponse trong cache với parser mới.
 * Không gọi AI, chỉ re-process data đã có.
 */
const fs   = require('fs');
const path = require('path');

const CACHE_FILE = path.join(__dirname, '..', 'cache', 'ai-rewrite-category-cache.json');
const MAIN_FILE  = path.join(__dirname, 'ai-rewrite-category.js');

// ── Load parseAIResponse via wrapper file ─────────────────────────────────────
// category-parser.js was generated by: node -e "..." (see generate-parser.js)
// Nếu chưa có, tự tạo lại
const PARSER_FILE = path.join(__dirname, 'category-parser-standalone.js');
if (!fs.existsSync(PARSER_FILE)) {
  const script   = fs.readFileSync(MAIN_FILE, 'utf8');
  const fnStart  = script.indexOf('function parseAIResponse');
  const fnEnd    = script.indexOf('\n// ── Validate', fnStart);
  const body     = script.slice(fnStart, fnEnd);
  fs.writeFileSync(PARSER_FILE, `'use strict';\n${body}\nmodule.exports = parseAIResponse;\n`);
}
const parseAIResponse = require(PARSER_FILE);

// ── Helpers ──────────────────────────────────────────────────────────────────
const stripH = h => (h || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
const wCount = h => stripH(h).split(/\s+/).filter(Boolean).length;

function validate(r) {
  if (!r) return ['Không parse được'];
  const issues = [];
  const wc = wCount(r.description);
  if (wc < 150)                             issues.push(`Desc ngắn (${wc}w)`);
  if (!/<h2/i.test(r.description))          issues.push('Thiếu <h2>');
  if (!/<ul/i.test(r.description))          issues.push('Thiếu <ul>');
  if (/<h1/i.test(r.description))           issues.push('Có <h1>');
  if (/\*\*/.test(r.description))           issues.push('Còn **bold**');
  if (/hãng b&r/i.test(r.description))      issues.push('"hãng b&r"');
  if (!/Agow Automation/i.test(r.description)) issues.push('Thiếu Agow');
  if (!/B&R/.test(r.description))           issues.push('Thiếu B&R');
  if (r.seoTitle.length > 62)               issues.push(`Title dài (${r.seoTitle.length}c)`);
  if (r.seoTitle.length < 30)               issues.push('Title ngắn');
  if (!/B&R/.test(r.seoTitle))              issues.push('Title thiếu B&R');
  if (!r.seoTitle.includes('|'))            issues.push('Title thiếu |');
  if (r.metaDesc.length > 162)              issues.push(`Meta dài (${r.metaDesc.length}c)`);
  if (r.metaDesc.length < 120)              issues.push('Meta ngắn');
  if (!/Agow/i.test(r.metaDesc))            issues.push('Meta thiếu Agow');
  return issues;
}

// ── Main ─────────────────────────────────────────────────────────────────────
const cache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf8'));
let fixed = 0;

for (const [id, v] of Object.entries(cache)) {
  if (!v.rawResponse) continue;
  const newResult = parseAIResponse(v.rawResponse);
  if (!newResult) continue;
  const newIssues = validate(newResult);
  const oldIssues = v.issues || [];

  const improved =
    newIssues.length < oldIssues.length ||
    (!v.result?.seoTitle && newResult.seoTitle) ||
    (wCount(v.result?.description || '') < wCount(newResult.description) && wCount(newResult.description) > 100);

  if (improved) {
    const wc  = wCount(newResult.description);
    const tag = newIssues.length ? `🟡 (${newIssues.length})` : '✅';
    console.log(`${tag} [${id}] ${(v.wcName || '').slice(0, 25).padEnd(25)} T:${newResult.seoTitle.length}c M:${newResult.metaDesc.length}c D:${wc}w`);
    if (newIssues.length) console.log(`   ${newIssues.join('; ')}`);
    v.result = newResult;
    v.issues = newIssues;
    fixed++;
  }
}

fs.writeFileSync(CACHE_FILE, JSON.stringify(cache, null, 2));

const clean  = Object.values(cache).filter(v => v.result && !v.issues?.length).length;
const review = Object.values(cache).filter(v => v.result &&  v.issues?.length).length;
const noRes  = Object.values(cache).filter(v => !v.result?.description).length;
console.log(`\nImproved: ${fixed} | ✅ Clean: ${clean} | 🟡 Review: ${review} | No result: ${noRes}`);
